### PR TITLE
Support for basic-2 cleaning

### PR DESCRIPTION
**Pull request by naofireblade**
Hey there,

you build a cool plugin. I use that for my homebridge-plugin [homebridge-neato](https://github.com/naofireblade/homebridge-neato).

Recently someone with a Neato D5 opened an issue that the plugin is not working. I checked the [neato developer page](https://developers.neatorobotics.com/api/robot-remote-protocol) and found out that they added a new parameter **navigationMode** in the recents services.

The API can handle two many parameters without a problem but strikes when a parameter is missing. So I added that parameter to the cleaning services. My Neato Botvac Connected just ignores the additional parameter but I'm pretty sure newer models that require this parameter will work now.
I hope you can merge that and publish it to npm so that my homebrige-plugin will work with newer models.

Best wishes
Arne

### CODE REVIEW

**Comment by Pmant** [comment]
Good finding, thanks!

**Comment by Pmant** [comment]
Published changes to npm (version 0.1.5).

**Comment by naofireblade** [comment]
Wow thanks, that was really fast. I updated my plugin and will tell you if the D5 can be controlled as soon as I get feedback.

**Comment by naofireblade** [comment]
I got positive feedback that it's working with the Neato D5 now.

**Pull request merged**
