### PR TITLE
Feature/persistent maps and boundaries

### PR DESCRIPTION
**Pull request by az0uz**
Added support for persistent maps and boundaries including:
- get the persistent maps
- get the boundaries
- set the boundaries
- clean a (polygon type) boundary (zone)

### CODE REVIEW

**Comment by Pmant** [comment]
ty for the PR! Could you clean up the README? The function parameters and callback parameters do not match the descriptions.

**Comment by ifeign** [comment]
Any updates on this?

**Comment by ifeign** [comment]
Is there anything I can do to help this PR get merged?

**Comment by ifeign** [comment]
@pmant I don't mean to be a bother, but this PR is holding back other projects that utilize node-botvac. Is there anything I can do to help this get merged?

**Comment by Pmant** [comment]
Sorry was on vacation. What prevented me from merging was this:

> ty for the PR! Could you clean up the README? The function parameters and callback parameters do not match the descriptions.

Will have a look at it tomorrow and merge if it's not to much work.

**Comment by ifeign** [comment]
I really appreciate you looking into this. I'm sorry to have repeatedly commented about this PR

**Pull request merged**
