### PR TITLE
Add robot property isBinFull

### PR DESCRIPTION
**Pull request by naofireblade**
This adds a property for the bin full alert. Change is successfully tested locally.

### CODE REVIEW

**Comment by Pmant** [comment]
Thank for your PRs! I merged the recent 3 PRs, including #18 from @PeterVoronov. Sadly I can't test this library right now, if you could confirm everything works as intended that would be great.

**Comment by naofireblade** [comment]
I can confirm that everything works. But you should swap the parameters **callback** and **detailed** in the getSchedule function because your library usually expects the callback as the last parameter.

**Comment by PeterVoronov** [comment]
> I can confirm that everything works. But you should swap the parameters **callback** and **detailed** in the getSchedule function because your library usually expects the callback as the last parameter.

If it will be switched, the backward compatibility will be broken, as it was requested by @Pmant and [you](https://github.com/Pmant/node-botvac/pull/16#issuecomment-829615564) @naofireblade ...

**Comment by Pmant** [comment]
I switched it including a parameter check, if any of you could confirm it works including backwards compatibility I will publish to npm.

**Comment by naofireblade** [comment]
All 3 request work perfectly fine:

Query:
```
this.robot.getSchedule((error, result) => {
	this.log.debug("Legacy: " +  result);
});
this.robot.getSchedule(false, (error, result) => {
	this.log.debug("Simple: " +  JSON.stringify(result));
});
this.robot.getSchedule(true, (error, result) => {
	this.log.debug("Detailed: " +  JSON.stringify(result));
});
```

Result:
```
[5/4/2021, 1:47:52 PM] [NeatoVacuumRobot] Legacy: false
[5/4/2021, 1:47:52 PM] [NeatoVacuumRobot] Simple: false
[5/4/2021, 1:47:52 PM] [NeatoVacuumRobot] Detailed: {"type":1,"enabled":false,"events":[{"day":2,"startTime":"12:59"},{"day":4,"startTime":"12:59"},{"day":6,"startTime":"12:59"}]}
```

**Comment by naofireblade** [comment]
PS: Thank you for the continued maintenance of the library. 👍

**Comment by PeterVoronov** [comment]
Yes. It's work ;-)

**Comment by PeterVoronov** [comment]
thank you

**Pull request merged**
